blank_issues_enabled: false
contact_links:
  - name: ⚠️ Application issue
    url: https://github.com/DokiTeam/Doki/issues/new/choose
    about: Issues and requests about the app itself should be opened in the Doki repository instead